### ISSUE TITLE
endian.go:36 ("array bound is not constant") & endian.go:37 ("array index out of bounds")

### ISSUE THREAD

**Issue by Geremia** [virtao/GoEndian#1]
I get these errors when trying to build [the sample code on the virtao/GoEndian homepage](https://github.com/virtao/GoEndian):
```
$go build endian.go
# github.com/virtao/GoEndian
../Documents/go/src/github.com/virtao/GoEndian/endian.go:36:11: error: array bound is not constant
  bs := (*[INT_SIZE]byte)(unsafe.Pointer(&i))
           ^
../Documents/go/src/github.com/virtao/GoEndian/endian.go:37:8: error: array index out of bounds
  if bs[0] == 0 {
        ^
```

**Comment by virtao** [comment]
What is your machine's CPU platform, and what is the version of the Go language?

Try delete the original GoEndian package in GOPATH, download the package again.

BTW: You can try the following steps to run the sample code.
1. go get github.com/virtao/GoEndian
2. mkdir sample && cd sample
3. Create “sample.go” and paste the sample code into "sample.go".
4. go run sample.go
